var ClassroomConstants = {
  ADD_STUDENT: "ADD_STUDENT",
  REMOVE_STUDENT: "REMOVE_STUDENT",
  MARK_ATTENDANCE: "MARK_ATTENDANCE",
  RAND_STUDENT: "RAND_STUDENT",
  RAND_GROUP: "RAND_GROUP",
  INIT_QUERY: "INIT_QUERY",
  END_QUERY: "END_QUERY",
  BEHAVIOR_CLICKED: "BEHAVIOR_CLICKED",
  GET_BEHAVIORS: "GET_BEHAVIORS",
  END_SELECT_QUERY: "END_SELECT_QUERY",
  GET_NEW_POKEMON: "GET_NEW_POKEMON",
};

module.exports = ClassroomConstants;
