var ClassroomConstants = {
  ADD_STUDENT: "ADD_STUDENT",
  REMOVE_STUDENT: "REMOVE_POINT",
  MARK_ATTENDANCE: "MARK_ATTENDANCE",
  INIT_QUERY: "INIT_QUERY",
  END_QUERY: "END_QUERY",
  BEHAVIOR_CLICKED: "BEHAVIOR_CLICKED"
};

module.exports = ClassroomConstants;
