var ClassroomConstants = {
  ADD_STUDENT: "ADD_STUDENT",
  REMOVE_STUDENT: "REMOVE_POINT",
  ADD_POINT: "ADD_POINT",
  MINUS_POINT: "SUBTRACT_POINT",
  MARK_ATTENDANCE: "MARK_ATTENDANCE",
  INIT_QUERY: "INIT_QUERY",
  END_QUERY: "END_QUERY"
};

module.exports = ClassroomConstants;
