var HomeworkConstants = {
  ADD_ASSIGNMENT: "ADD_ASSIGNMENT",
  INIT_QUERY: "INIT_QUERY",
  END_QUERY: "END_QUERY",
  REMOVE_ASSIGNMENT: "REMOVE_ASSIGNMENT",
  PAST_ASSIGNMENTS: "PAST_ASSIGNMENTS",
  MONTH_SELECTED: "MONTH_SELECTED",
  ADD_STUDENT_EMAIL: "ADD_STUDENT_EMAIL"
};

module.exports = HomeworkConstants;
