var HomeworkConstants = {
  ADD_ASSIGNMENT: "ADD_ASSIGNMENT",
  INIT_QUERY: "INIT_QUERY",
  END_QUERY: "END_QUERY",
  REMOVE_ASSIGNMENT: "REMOVE_ASSIGNMENT",
  PAST_ASSIGNMENTS: "PAST_ASSIGNMENTS"
};

module.exports = HomeworkConstants;
